---
- name: Get ZFS
  get_url: url=https://openzfsonosx.org/w/images/6/6f/OpenZFS_on_OS_X_1.9.4.dmg dest=/tmp/OpenZFS_on_OS_X_1.9.4.dmg
- name: Mount ZFS
  command: hdiutil attach /tmp/OpenZFS_on_OS_X_1.9.4.dmg -nobrowse -mountpoint /Volumes/OpenZFS_on_OS_X_1.9.4
- name: Install PKG
  become: true
  shell: "installer -pkg /Volumes/OpenZFS_on_OS_X_1.9.4/OpenZFS\ on\ OS\ X\ 1.9.4\ Catalina.pkg -target /"
- name: Unmount DMG
  command: hdiutil detach /Volumes/OpenZFS_on_OS_X_1.9.4