---
# Mostly taken from geerlingguy/mac-dev-playbook
name: Ansible testing
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint
      - name: Lint code.
        run: |
          yamllint .
  ansible:
    name: Ansible setup
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Manpages Error for OpenZFS Fix
        run: | 
          sudo chown -R $(whoami) /usr/local/share/man/man8
          chmod u+w /usr/local/share/man/man8
      - name: Remove Homebrew
        run: ./.github/workflows/uninstall-homebrew.sh
      - name: Install ansible
        run: sudo pip3 install ansible
      - name: Copy in test configuration
        run: |
          cp ./tests/ansible.cfg ./ansible.cfg
          cp ./tests/inventory ./inventory
          cp ./tests/default.config.yml ./default.config.yml
          ansible-galaxy install -r requirements.yml -p ./roles
      - name: Syntax checker
        run: ansible-playbook main.yml --syntax-check
      - name: Run Playbook
        run: ansible-playbook --become-user=root main.yml 
        env:
          ANSIBLE_FORCE_COLOR: '1'
      - name: Packages Installed?
        run: |
          opam --version
          ls ~/ocaml
